development:
  adapter: postgresql
  database: mitchdzugancom
  pool: 5
  timeout: 5000
  username: postgres
  password: testdb
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: somedatabase_dev
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test: &test
  adapter: postgresql
  database: mitchdzugancom_test
  pool: 5
  timeout: 5000
  username: postgres
  password: testdb
  host: localhost
